// Keep level at 40+
// Level determined by how confident and expeditious I am at finding solutions.
var skills = [
    {skill: 'Python', level: 100},
    {skill: 'KnockoutJS MVVM', level: 100},
    {skill: 'MySQL', level: 90},
    {skill: 'PostgreSQL', level: 90},
    {skill: 'JavaScript', level: 90},
    {skill: 'Bootstrap', level: 90},
    {skill: 'SailsJS / Waterline ORM', level: 80},
    {skill: 'Sphinx', level: 80},
    {skill: 'Git', level: 80},
    {skill: 'GruntJS', level: 80},
    {skill: 'Java', level: 80},
    {skill: 'Google App Engine', level: 80},
    {skill: 'Lightroom', level: 80},
    {skill: 'R + RMarkdown', level: 70},
    {skill: 'ENVI / IDL', level: 70},
    {skill: 'SQLAlchemy ORM', level: 70},
    {skill: 'Flask Microframework', level: 70},
    {skill: 'Image Processing', level: 70},
    {skill: '3D Reconstruction', level: 70},
    {skill: 'OpenCV', level: 70},
    {skill: 'Unit Testing', level: 60},
    {skill: 'Photoshop', level: 60},
    {skill: 'Linux / Ubuntu', level: 50},
    {skill: 'QGIS', level: 50},
    {skill: 'ArcGIS', level: 40},
    {skill: 'EmbeddedJS', level: 40},
]
